version: '3'
services:

    loja-postgres:
        image: "postgres:9.6-alpine"
        container_name: loja-postgres
        volumes:
        - loja-data:/var/lib/postgresql/data
        ports:
        - 5432:5432
        environment:
        - POSTGRES_DB=loja_virtual
        - POSTGRES_USER=default
        - POSTGRES_PASSWORD=secret
        networks:
            - dev-network

    backend:
        build: ./backend
        container_name: backend
        environment:
            - DB_SERVER=loja-postgres
            - POSTGRES_DB=loja_virtual
            - POSTGRES_USER=default
            - POSTGRES_PASSWORD=secret
        ports:
            - 8080:8080
        links:
            - loja-postgres
        networks:
            - dev-network

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - 4200:80
        links:
            - backend
        networks:
            - dev-network


volumes:
  loja-data:
networks: 
    dev-network:
        driver: bridge
